### ISSUE TITLE
Default F6 is conflicted with ST3 F6 default action Spell Check

### ISSUE THREAD

**Issue by phts** [HackerBaloo/SublimeHexConverter#2]
As a workaround copy a string from default key-mappings file

```
{ "keys": ["f6"], "command": "toggle_setting", "args": {"setting": "spell_check"} },
```

to a user key-mappings file and then add a new key-mapping for old one of Hex Converter

```
{"keys": ["f6"], "command": "convert_to_from_hex"}
```

**Comment by HackerBaloo** [comment]
Thank you, I have now changed the default key binding to "alt+shift+h".

**Comment by phts** [comment]
> I have now changed the default key binding to "alt+shift+h"

Closed in this case.
